title: Portfolio
timezone: America/New_York
markdown: kramdown

collections:
  experience:
    output: true
    permalink: /experience/:slug/
  works:
    output: true
    permalink: /works/:slug/
  awards:
    output: true
    permalink: /awards/:slug/
  media:
    output: true
    permalink: /media/:slug/
  patents:
    output: true
    permalink: /patents/:slug/
