name: Sync Notion to JSON
on:
  schedule:
    - cron: "0 */6 * * *"   # 6時間おき
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install deps
        run: npm i @notionhq/client
      - name: Generate public/notion.json
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
        run: node scripts/fetch-notion.js
      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/notion.json
          git diff --quiet || git commit -m "chore: update notion data"
          git push
